### ISSUE TITLE
Development & Review Progress Tracker

### ISSUE THREAD

**Issue by AHolder1** [CAWaterBoardDataCenter/swamp-manual#2]
[Welcome!](https://cawaterboarddatacenter.github.io/swamp-manual/)
- [x] Confirm content is moved over from SharePoint doc @AHolder1 
- [x] Review/Edit: [ADD @ IF YOU WANT TO REVIEW/EDIT] @DevanBurke 

[About SWAMP](https://cawaterboarddatacenter.github.io/swamp-manual/about-swamp.html)
- [x] Confirm content is moved over from SharePoint doc @AHolder1 
- [ ] Review/Edit: [ADD @ IF YOU WANT TO REVIEW/EDIT]

[Values](https://cawaterboarddatacenter.github.io/swamp-manual/values.html)
- [ ] Add content to page
- [ ] Review/Edit: [ADD @ IF YOU WANT TO REVIEW/EDIT]

[Code of Content](https://cawaterboarddatacenter.github.io/swamp-manual/codeofconduct.html)
- [ ] Add content to page
- [ ] Review/Edit: [ADD @ IF YOU WANT TO REVIEW/EDIT]

[Expectations](https://cawaterboarddatacenter.github.io/swamp-manual/expectations.html)
- [x] Confirm content is moved over from SharePoint doc @AHolder1 
- [ ] Review/Edit: [ADD @ IF YOU WANT TO REVIEW/EDIT]

[Professional Development](https://cawaterboarddatacenter.github.io/swamp-manual/development.html)
- [x] Confirm content is moved over from SharePoint doc @AHolder1 
- [ ] Review/Edit: [ADD @ IF YOU WANT TO REVIEW/EDIT]

[Onboarding](https://cawaterboarddatacenter.github.io/swamp-manual/onboarding.html)
- [x] Confirm content is moved over from SharePoint doc @AHolder1 
- [x] Finish adding content to page
- [ ] Review/Edit: [ADD @ IF YOU WANT TO REVIEW/EDIT]

[Travel](https://cawaterboarddatacenter.github.io/swamp-manual/travel.html)
- [x] Confirm content is moved over from SharePoint doc @AHolder1 
- [ ] Review/Edit: [ADD @ IF YOU WANT TO REVIEW/EDIT]

[Training](https://cawaterboarddatacenter.github.io/swamp-manual/training.html)
- [x] Confirm content is moved over from SharePoint doc @AHolder1 
- [ ] Review/Edit: [ADD @ IF YOU WANT TO REVIEW/EDIT]

[Tech Access, Setup, & Support](https://cawaterboarddatacenter.github.io/swamp-manual/tech.html)
- [x] Confirm content is moved over from SharePoint doc @AHolder1 
- [ ] Finish adding content to page
- [ ] Review/Edit: [ADD @ IF YOU WANT TO REVIEW/EDIT]

[Procurement](https://cawaterboarddatacenter.github.io/swamp-manual/procurement.html)
- [x] Confirm content is moved over from SharePoint doc @AHolder1 
- [ ] Finish adding content to page
- [ ] Review/Edit: [ADD @ IF YOU WANT TO REVIEW/EDIT]

[Offboarding](https://cawaterboarddatacenter.github.io/swamp-manual/offboarding.html)
- [x] Confirm content is moved over from SharePoint doc @AHolder1 
- [ ] Finish adding content to page
- [ ] Review/Edit: [ADD @ IF YOU WANT TO REVIEW/EDIT]

[SWAMP Life Cycle](https://cawaterboarddatacenter.github.io/swamp-manual/lifecycle.html)
- [x] Confirm content is moved over from SharePoint doc @AHolder1 
- [x] Review/Edit: [ADD @ IF YOU WANT TO REVIEW/EDIT]

[Meet the SWAMP Team!](https://cawaterboarddatacenter.github.io/swamp-manual/contacts.html)
- [x] Confirm content is moved over from SharePoint doc @AHolder1 
- [ ] Finish adding content to page
- [ ] Review/Edit: [ADD @ IF YOU WANT TO REVIEW/EDIT]

[Contributing](https://cawaterboarddatacenter.github.io/swamp-manual/contribute.html)
- [x] Confirm content is moved over from SharePoint doc @AHolder1 
- [ ] Review/Edit: [ADD @ IF YOU WANT TO REVIEW/EDIT]

[Inspiration](https://cawaterboarddatacenter.github.io/swamp-manual/inspiration.html)
- [ ] Review/Edit: [ADD @ IF YOU WANT TO REVIEW/EDIT]

[References](https://cawaterboarddatacenter.github.io/swamp-manual/references.html)
- [ ] Add content to page
- [ ] Review/Edit: [ADD @ IF YOU WANT TO REVIEW/EDIT]

**Comment by AHolder1** [comment]
It's been a while since we've used this issue (2023!) - We're in a totally different development/review/revise space now so, I'm going to close this issue and we can use the new issues we're creating as a guide.
